environment:
  matrix:
    - PYTHON: "C:\\Python26"
    - PYTHON: "C:\\Python26-x64"
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33"
    # https://bugs.python.org/issue7511
    #- PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    #- PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

build: off

install:
    - git --version
    - '%PYTHON%\python.exe --version'
    - git submodule update --init --recursive
    - '%PYTHON%\scripts\pip.exe install wheel'
    - '%PYTHON%\scripts\pip.exe --version'

test_script:
    - '%PYTHON%\python.exe setup.py test'

after_test:
    - '%PYTHON%\python.exe setup.py bdist_wheel'
    - '%PYTHON%\python.exe setup.py bdist_wininst'
    - '%PYTHON%\python.exe setup.py bdist_msi'
    - ps: ls dist

artifacts:
    - path: dist\*
