max_jobs: 2

environment:
  global:
    PYPI_USER: ifduyue
    PYPI_TEST_PASSWORD:
      secure: Ub5TGKonq/xFgzRLFMCcKQ==
    PYPI_PASSWORD:
      secure: fFfFN5N5920gtX3+pwrOddk/psDk3wK67snCOt209bc=
    PYTHONUNBUFFERD: 1
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "32"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    # build wheels
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      XXHASH_BUILDWHEELS: 1

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - git --version
  - python --version
  - pip --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - git submodule update --init --recursive
  - pip install wheel
  - set

test_script:
  - python setup.py build_ext --inplace
  - pip install pytest
  - python -m pytest
  #- cibuildwheel --output-dir wheels
  #- ls wheels
  - ps: |
      if (Test-Path env:XXHASH_BUILDWHEELS) {
        python -m pip install -U pip setuptools cibuildwheel
        cibuildwheel --output-dir wheels
        ls wheels
      }

artifacts:
  - path: wheels\*.whl
    name: Wheels


on_success:
  # deploy master non-tags to Test PyPI
  - ps: |
      if (!(Test-Path env:XXHASH_BUILDWHEELS)) { return }
      if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) { return }
      if ($env:APPVEYOR_REPO_NAME -ne 'ifduyue/python-xxhash') { return }
      if ($env:APPVEYOR_REPO_BRANCH -ne 'master') { return }
      pip install -U twine
      twine upload -u $env:PYPI_USER -p $env:PYPI_TEST_PASSWORD --repository-url https://test.pypi.org/legacy/ --skip-existing wheels\*.whl

  # deploy tags to PyPI
  - ps: |
      if (!(Test-Path env:XXHASH_BUILDWHEELS)) { return }
      if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) { return }
      if ($env:APPVEYOR_REPO_NAME -ne 'ifduyue/python-xxhash') { return }
      if ($env:APPVEYOR_REPO_TAG -ne 'true') { return }
      pip install -U twine
      twine upload -u $env:PYPI_USER -p $env:PYPI_PASSWORD --skip-existing wheels\*.whl
