max_jobs: 2

environment:
  global:
    PYPI_USER: ifduyue
    PYPI_TEST_PASSWORD:
      secure: Ub5TGKonq/xFgzRLFMCcKQ==
    PYPI_PASSWORD:
      secure: fFfFN5N5920gtX3+pwrOddk/psDk3wK67snCOt209bc=
    PYTHONUNBUFFERD: 1
  matrix:
    - PYTHON: "C:\\Python26"
      PYTHON_VERSION: "2.6"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python26-x64"
      PYTHON_VERSION: "2.6"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3"
      PYTHON_ARCH: "32"
    # https://bugs.python.org/issue7511
    #- PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
    #- PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
    # build wheels
    #- PYTHON: "C:\\Python36-x64"
    #  PYTHON_VERSION: "3.6"
    #  PYTHON_ARCH: "64"
    #  XXHASH_BUILDWHEELS: 1

build: off

install:
  - git --version
  - python --version
  - '%PYTHON%\python.exe --version'

  - git submodule update --init --recursive
  - '%PYTHON%\scripts\pip.exe install wheel'
  - '%PYTHON%\scripts\pip.exe --version'
  - set

test_script:
  - '%PYTHON%\python.exe setup.py test'
  #- cibuildwheel --output-dir wheels
  #- ls wheels
  - ps: |
      if (Test-Path env:XXHASH_BUILDWHEELS) {
        python -m pip install -U pip setuptools cibuildwheel
        cibuildwheel --output-dir wheels
        ls wheels
      }

artifacts:
  - path: wheels\*.whl
    name: Wheels


on_success:
  # deploy master non-tags to Test PyPI
  - ps: |
      if (!(Test-Path env:XXHASH_BUILDWHEELS)) { return }
      if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) { return }
      if ($env:APPVEYOR_REPO_NAME -ne 'ifduyue/python-xxhash') { return }
      if ($env:APPVEYOR_REPO_BRANCH -ne 'master') { return }
      pip install -U twine
      twine upload -u $env:PYPI_USER -p $env:PYPI_TEST_PASSWORD --repository-url https://test.pypi.org/legacy/ --skip-existing wheels\*.whl

  # deploy tags to PyPI
  - ps: |
      if (!(Test-Path env:XXHASH_BUILDWHEELS)) { return }
      if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) { return }
      if ($env:APPVEYOR_REPO_NAME -ne 'ifduyue/python-xxhash') { return }
      if ($env:APPVEYOR_REPO_TAG -ne 'true') { return }
      pip install -U twine
      twine upload -u $env:PYPI_USER -p $env:PYPI_PASSWORD --skip-existing wheels\*.whl
