language: python
python: 3.8
dist: xenial

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
    - python: nightly
  include:
    - python: 2.6
      arch: amd64
      dist: trusty
    - python: 2.7
      arch: amd64
    - python: 2.7
      arch: arm64
    - python: 3.3
      arch: amd64
      dist: trusty
    - python: 3.4
      arch: amd64
    - python: 3.4
      arch: arm64
    - python: 3.5
      arch: amd64
    - python: 3.5
      arch: arm64
    - python: 3.6
      arch: amd64
    - python: 3.6
      arch: arm64
    - python: 3.7
      arch: amd64
    - python: 3.7
      arch: arm64
    - python: 3.8
      arch: amd64
    - python: 3.8
      arch: arm64
    - python: 3.9
      arch: amd64
    - python: 3.9
      arch: arm64
    - python: nightly
      arch: amd64
    - python: pypy
      arch: amd64
    - python: pypy
      arch: arm64
    - python: pypy3
      arch: amd64
    - python: pypy3
      arch: arm64
    # linux wheels
    - dist: xenial
      arch: amd64
      python: 3.7
      sudo: required
      services:
        - docker
      env: XXHASH_BUILDWHEELS=1
    # linux arm wheels
    - dist: xenial
      arch: arm64
      python: 3.7
      sudo: required
      services:
        - docker
      env: XXHASH_BUILDWHEELS=1
    # osx wheels
    - os: osx
      osx_image: xcode9.4
      language: generic
      env: XXHASH_BUILDWHEELS=1
      before_install:
        - SSL_CERT_FILE=$(brew --prefix)/etc/openssl/cert.pem
        - sudo pip install -U pip setuptools twine

install:
  - gcc --version
  - |
    if [ -n "${XXHASH_BUILDWHEELS:-}" ]; then
      pip3 install cibuildwheel==1.7.0
    fi

script:
  - |
    if [ -n "${XXHASH_BUILDWHEELS:-}" ]; then
      cibuildwheel --output-dir dist
      ls dist/
    else
      python setup.py build_ext --inplace
      pip install pytest
      python -m pytest
      ./bench.sh
    fi

deploy:
  # deploy master non-tags to Test PyPI
  - provider: pypi
    user: ifduyue
    password:
      secure: "AKWSOlvoiBvXkUJYg/WWueMDON9EmUXgy5GIO1LFhXGmWChHaEuLRhjn9PtU0GUeaUIUGPwleTbF9YMUiXr0zCCjllV6hNGwJ/wrRNfI6+I0m4YLTjS5uQ4/P0uhPCNIroD1YI9GtLtySdyvmOJI4wDxEd57gycHE47re3jwF90="
    server: https://test.pypi.org/legacy/
    distributions: sdist
    skip_existing: true
    skip_cleanup: true
    on:
      repo: ifduyue/python-xxhash
      tags: false
      branch: master
      condition: -n "${XXHASH_BUILDWHEELS:-}"

  # deploy tags to PyPI
  - provider: pypi
    user: ifduyue
    password:
      secure: "SJCAFtJKqpPl1P8idrPMJYpON6aNpLFB1cMq6uaLW16a3pGsHPu533sP8U+t7P+rmMNP1mmkmuQyJKKUWOqjdj3FrKpHqgh7V2FwvRcucModsGU3DXm28R0RRGtJ4XVct6YWaDzlwi2sdGwtMNEGdtbGOmUa3gJNyuDPWgonwgM="
    distributions: sdist
    skip_existing: true
    skip_cleanup: true
    on:
      repo: ifduyue/python-xxhash
      tags: true
      condition: -n "${XXHASH_BUILDWHEELS:-}"
